"""All tables

Revision ID: 7d508eb85503
Revises: 55275b8c24cc
Create Date: 2024-12-17 21:03:57.798008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from project.core.config import settings


# revision identifiers, used by Alembic.
revision: str = '7d508eb85503'
down_revision: Union[str, None] = '55275b8c24cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education_organization',
    sa.Column('education_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_name', sa.CHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('education_id'),
    schema=settings.POSTGRES_SCHEMA
    )
    op.create_table('employers',
    sa.Column('employer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employer_name', sa.CHAR(length=50), nullable=False),
    sa.Column('contact_name', sa.CHAR(length=50), nullable=True),
    sa.Column('phone', sa.CHAR(length=20), nullable=True),
    sa.Column('email', sa.CHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('employer_id'),
    schema=settings.POSTGRES_SCHEMA
    )
    op.create_table('skills',
    sa.Column('skill_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('skill_name', sa.CHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('skill_id'),
    schema=settings.POSTGRES_SCHEMA
    )
    op.create_table('candidates_education',
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('education_id', sa.Integer(), nullable=False),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('degree', sa.CHAR(length=50), nullable=True),
    sa.Column('field_of_study', sa.CHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], [f"{settings.POSTGRES_SCHEMA}.candidates.candidate_id"], ),
    sa.ForeignKeyConstraint(['education_id'], [f"{settings.POSTGRES_SCHEMA}.education_organization.education_id"], ),
    sa.PrimaryKeyConstraint('candidate_id', 'education_id'),
    schema=settings.POSTGRES_SCHEMA
    )
    op.create_table('candidates_skills',
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], [f"{settings.POSTGRES_SCHEMA}.candidates.candidate_id"], ),
    sa.ForeignKeyConstraint(['skill_id'], [f"{settings.POSTGRES_SCHEMA}.skills.skill_id"], ),
    sa.PrimaryKeyConstraint('candidate_id', 'skill_id'),
    schema=settings.POSTGRES_SCHEMA
    )
    op.create_table('resumes',
    sa.Column('resume_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.CHAR(length=50), nullable=False),
    sa.Column('work_experience', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('date_created', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], [f"{settings.POSTGRES_SCHEMA}.candidates.candidate_id"], ),
    sa.PrimaryKeyConstraint('resume_id'),
    schema=settings.POSTGRES_SCHEMA
    )
    op.create_table('vacancies',
    sa.Column('vacancy_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employer_id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.CHAR(length=50), nullable=False),
    sa.Column('salary', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('work_experience', sa.Integer(), nullable=False),
    sa.Column('status_open', sa.Boolean(), nullable=True),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('date_posted', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['employer_id'], [f"{settings.POSTGRES_SCHEMA}.employers.employer_id"], ),
    sa.PrimaryKeyConstraint('vacancy_id'),
    schema=settings.POSTGRES_SCHEMA
    )
    op.create_table('accepted_person',
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('vacancy_id', sa.Integer(), nullable=False),
    sa.Column('date_of_acceptance', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], [f"{settings.POSTGRES_SCHEMA}.candidates.candidate_id"], ),
    sa.ForeignKeyConstraint(['vacancy_id'],  [f"{settings.POSTGRES_SCHEMA}.vacancies.vacancy_id"], ),
    sa.PrimaryKeyConstraint('candidate_id', 'vacancy_id'),
    schema=settings.POSTGRES_SCHEMA
    )
    op.create_table('resume_vacancies',
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('vacancy_id', sa.Integer(), nullable=False),
    sa.Column('date_applied', sa.Date(), nullable=False),
    sa.Column('status_approved', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'],  [f"{settings.POSTGRES_SCHEMA}.resumes.resume_id"], ),
    sa.ForeignKeyConstraint(['vacancy_id'], [f"{settings.POSTGRES_SCHEMA}.vacancies.vacancy_id"], ),
    sa.PrimaryKeyConstraint('resume_id', 'vacancy_id'),
    schema=settings.POSTGRES_SCHEMA
    )
    op.create_table('vacancy_skills',
    sa.Column('vacancy_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], [f"{settings.POSTGRES_SCHEMA}.skills.skill_id"], ),
    sa.ForeignKeyConstraint(['vacancy_id'], [f"{settings.POSTGRES_SCHEMA}.vacancies.vacancy_id"], ),
    sa.PrimaryKeyConstraint('vacancy_id', 'skill_id'),
    schema=settings.POSTGRES_SCHEMA
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacancy_skills', schema=settings.POSTGRES_SCHEMA)
    op.drop_table('resume_vacancies', schema=settings.POSTGRES_SCHEMA)
    op.drop_table('accepted_person', schema=settings.POSTGRES_SCHEMA)
    op.drop_table('vacancies', schema=settings.POSTGRES_SCHEMA)
    op.drop_table('resumes', schema=settings.POSTGRES_SCHEMA)
    op.drop_table('candidates_skills', schema=settings.POSTGRES_SCHEMA)
    op.drop_table('candidates_education', schema=settings.POSTGRES_SCHEMA)
    op.drop_table('skills', schema=settings.POSTGRES_SCHEMA)
    op.drop_table('employers', schema=settings.POSTGRES_SCHEMA)
    op.drop_table('education_organization', schema=settings.POSTGRES_SCHEMA)
    # ### end Alembic commands ###
