from .candidate import CandidateSchema
from .employer import EmployerSchema
from .vacancy import VacancySchema
from .resume import ResumeSchema
from .skill import SkillSchema
from .vacancy_skill import VacancySkillSchema
from .education_organization import EducationOrganizationSchema
from .candidate_education import CandidateEducationSchema
from .candidate_skill import CandidateSkillSchema
from .resume_vacancy import ResumeVacancySchema
from .accepted_person import AcceptedPersonSchema
